FROM almalinux:9
ENV COURSE="DevOps" \
    DURATION="120HRS" \
    TRAINER="SivaKumar"
CMD [ "sleep", "100" ]
#here we have to give any command to make sure container is doing some work or else environment varibales will not work and container will be exited thinking there is nothing to do 